services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=KanChessDatabase'
      - 'POSTGRES_PASSWORD=SecretPassword'
      - 'POSTGRES_USER=Kan'
    ports:
      - '5431:5432'
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  db-data: